force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <description>Loan Details</description>
    <label>Loan</label>
    <nameField>
        <displayFormat>LId-{0000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/No_of_EMI_s__c.field-meta.xml
<CustomField>
    <fullName>No_of_EMI_s__c</fullName>
    <formula>CASE(Type_Of_Loan__c , 
       &apos;Education&apos;, 48,
       &apos;Housing&apos;, 120,
       &apos;Personal&apos;, 32,
        0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No. of EMI&apos;s</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Security__c.field-meta.xml
<CustomField>
    <fullName>Security__c</fullName>
    <label>Security</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salary</fullName>
            </value>
            <value>
                <fullName>Assert</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Type_Of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Loan__c</fullName>
    <label>Type Of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PID-{000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Child_Parent_SOQL.cls
// Class : 13 Child Parent SOQL
public class Child_Parent_SOQL {
    public static void childParentSOQL(){
        
        // If Relation Field is Standard Field
        // --------------------------------------
        // Get Cases with corresponding Account Records.
        List<Case> lstCases = [SELECT Id, Status, Subject, Priority,
                              Account.Name, Account.Rating, Account.Industry
                              FROM Case];
        
        // If Relation Field is Custom Field
        // --------------------------------------
        // Get all Payments with corresponding Customer Records.
        List<Payment__c> lstPayments = [SELECT Id, Name, City__c, Loan__c, Amount__c,
                                       Customer__r.Name, Customer__r.City__c, Customer__r.Age__c, Customer__r.Email__c
                                       FROM Payment__c];
        
        // Get all Loans with corresponding Customer Records
        List<Loan__c> lstLoans1 = [SELECT Id, Name, Type_Of_Loan__c, No_of_EMI_s__c, Security__c,
                                 Customer__r.Name, Customer__r.City__c, Customer__r.Age__c, Customer__r.Email__c // Custom Relation with Customer
                                 FROM Loan__c];
        
        
        // Get all Loans with correspsonding Customer Records and User Data
        // If we have 2-3 Relation Field, we can refer to multiple Parents at a time. 
        List<Loan__c> lstLoans2 = [SELECT Id, Name, Type_Of_Loan__c, No_of_EMI_s__c, Security__c,
                                 Customer__r.Name, Customer__r.City__c, Customer__r.Age__c, Customer__r.Email__c, // Custom Relation with Customer
                                 CreatedBy.Name, LastModifiedBy.Name // Standard Relation With User
                                 FROM Loan__c];
        
    }
}